### ISSUE TITLE
Rewrite on top of React DnD

### ISSUE THREAD

**Issue by samvtran** [samvtran/react-sortable-items#4]
This will also take care of the upcoming changes in 0.14 deprecating cloneWithProps so nothing needs to be done there.
- [ ] Update dependencies (#5)
- [ ] Redux-like API options (i.e., mixin, function, and decorator) (#6)
- [ ] Multiple targets (#12)
- [ ] Update to React 0.14 (#7)
- [ ] Touch interface via https://github.com/yahoo/react-dnd-touch-backend (#8)
- [ ] New docs (#9)
- [ ] New examples (#10)
- [ ] Tests (#11)
- [ ] Support nesting

Sortable props to port over:
- [ ] horizontal (probably as a string field for specifying grid as well or as a separate HOC)
- [ ] onSort
- [ ] minDragDistance

SortableItemMixin props to port over:
- [ ] isDraggable (A wrapper around canDrag)
- [ ] sortData
